# Generated by Django 6.0.3 on 2026-03-13 06:55

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('original_name', models.CharField(max_length=255)),
                ('file_size', models.IntegerField()),
                ('mime_type', models.CharField(max_length=100)),
                ('is_malicious', models.BooleanField(default=False)),
                ('scan_status', models.CharField(default='pending', max_length=20)),
                ('scan_result', models.JSONField(default=dict)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'attachments',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('academic_level', models.CharField(choices=[('high_school', 'high_school'), ('undergraduate', 'undergraduate'), ('masters', 'masters'), ('phd', 'phd')], max_length=20)),
                ('paper_type', models.CharField(choices=[('essay', 'essay'), ('research_paper', 'research_paper'), ('term_paper', 'term_paper'), ('thesis', 'thesis'), ('dissertation', 'dissertation'), ('case_study', 'case_study'), ('coursework', 'coursework')], max_length=20)),
                ('subject', models.CharField(max_length=100)),
                ('topic', models.TextField()),
                ('pages', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('words', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('deadline', models.DateTimeField(db_index=True)),
                ('sources', models.CharField(max_length=50)),
                ('format', models.CharField(choices=[('apa', 'apa'), ('mla', 'mla'), ('chicago', 'chicago'), ('harvard', 'harvard'), ('ieee', 'ieee')], max_length=20)),
                ('instructions', models.TextField()),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('urgency_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('extras_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plagiarism_report', models.BooleanField(default=False)),
                ('abstract', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('ongoing', 'ongoing'), ('awaiting_review', 'awaiting_review'), ('completed', 'completed'), ('cancelled', 'cancelled'), ('refund_pending', 'refund_pending')], db_index=True, default='pending', max_length=20)),
                ('progress_percentage', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('auto_approve_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('cancellation_category', models.CharField(blank=True, max_length=50)),
                ('revision_count', models.IntegerField(default=0)),
                ('last_revision_requested_at', models.DateTimeField(blank=True, null=True)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('refund_reason', models.TextField(blank=True)),
                ('grade_received', models.CharField(blank=True, max_length=10)),
                ('refund_approved_at', models.DateTimeField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('feedback', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attachments', models.ManyToManyField(blank=True, related_name='orders', to='orders.attachment')),
                ('cancellation_evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancellation_evidence', to='orders.attachment')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_orders', to=settings.AUTH_USER_MODEL)),
                ('delivered_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivered_orders', to='orders.attachment')),
                ('plagiarism_report_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plagiarism_orders', to='orders.attachment')),
                ('refund_evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_evidence', to='orders.attachment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=50)),
                ('from_status', models.CharField(blank=True, max_length=20, null=True)),
                ('to_status', models.CharField(blank=True, max_length=20, null=True)),
                ('data', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='orders.order')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'order_history',
            },
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['uploaded_by', 'uploaded_at'], name='attachments_uploade_c2e865_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['is_malicious'], name='attachments_is_mali_aa03b6_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['scan_status'], name='attachments_scan_st_60b515_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['student', 'status'], name='orders_student_277d4a_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['student', 'created_at'], name='orders_student_9a9891_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'deadline'], name='orders_status_a2165e_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['auto_approve_at'], name='orders_auto_ap_b576ca_idx'),
        ),
        migrations.AddIndex(
            model_name='orderhistory',
            index=models.Index(fields=['order', 'created_at'], name='order_histo_order_i_86f11e_idx'),
        ),
        migrations.AddIndex(
            model_name='orderhistory',
            index=models.Index(fields=['action'], name='order_histo_action_b7484a_idx'),
        ),
    ]
