# Generated by Django 6.0.3 on 2026-03-13 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='attachment',
            name='attachments_is_mali_aa03b6_idx',
        ),
        migrations.RenameField(
            model_name='attachment',
            old_name='original_name',
            new_name='filename',
        ),
        migrations.RenameField(
            model_name='attachment',
            old_name='is_malicious',
            new_name='is_corrupt',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cancellation_category',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cancellation_evidence',
        ),
        migrations.RemoveField(
            model_name='order',
            name='refund_evidence',
        ),
        migrations.RemoveField(
            model_name='order',
            name='sources',
        ),
        migrations.RemoveField(
            model_name='order',
            name='urgency_multiplier',
        ),
        migrations.AddField(
            model_name='attachment',
            name='corruption_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='attachment',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='order',
            name='links',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='order',
            name='one_page_summary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='preferred_writer_level',
            field=models.CharField(choices=[('any', 'any'), ('master', 'master'), ('phd', 'phd')], default='any', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='proofreading',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='sources_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='writer_premium',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to='attachments/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='scan_status',
            field=models.CharField(choices=[('pending', 'pending'), ('scanning', 'scanning'), ('clean', 'clean'), ('infected', 'infected'), ('corrupt', 'corrupt'), ('failed', 'failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='paper_type',
            field=models.CharField(choices=[('essay', 'essay'), ('research_paper', 'research_paper'), ('term_paper', 'term_paper'), ('thesis', 'thesis'), ('dissertation', 'dissertation'), ('case_study', 'case_study'), ('coursework', 'coursework'), ('lab_report', 'lab_report'), ('book_review', 'book_review'), ('article', 'article')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='subject',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='topic',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='action',
            field=models.CharField(choices=[('create', 'create'), ('approve', 'approve'), ('start', 'start'), ('deliver', 'deliver'), ('complete', 'complete'), ('cancel', 'cancel'), ('reject', 'reject'), ('refund_request', 'refund_request'), ('refund_approve', 'refund_approve'), ('refund_deny', 'refund_deny'), ('revise', 'revise'), ('update', 'update')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['is_corrupt'], name='attachments_is_corr_35c310_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['file_hash'], name='attachments_file_ha_ad54cc_idx'),
        ),
    ]
