# Generated by Django 5.2.16 on 2026-07-24 12:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_attachment_attachments_is_mali_aa03b6_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='approved_at',
            new_name='accepted_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='abstract',
        ),
        migrations.RemoveField(
            model_name='order',
            name='base_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='extras_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='one_page_summary',
        ),
        migrations.RemoveField(
            model_name='order',
            name='plagiarism_report',
        ),
        migrations.RemoveField(
            model_name='order',
            name='plagiarism_report_file',
        ),
        migrations.RemoveField(
            model_name='order',
            name='preferred_writer_level',
        ),
        migrations.RemoveField(
            model_name='order',
            name='proofreading',
        ),
        migrations.RemoveField(
            model_name='order',
            name='writer_premium',
        ),
        migrations.AddField(
            model_name='order',
            name='escrow_released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='slides',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='order',
            name='writer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='writer_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='format',
            field=models.CharField(choices=[('apa', 'apa'), ('mla', 'mla'), ('chicago', 'chicago'), ('harvard', 'harvard'), ('turabian', 'turabian'), ('vancouver', 'vancouver'), ('oscola', 'oscola'), ('ieee', 'ieee')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='paper_type',
            field=models.CharField(choices=[('essay', 'essay'), ('research_paper', 'research_paper'), ('dissertation', 'dissertation'), ('thesis', 'thesis'), ('case_study', 'case_study'), ('literature_review', 'literature_review'), ('article_review', 'article_review'), ('book_report', 'book_report'), ('speech', 'speech'), ('presentation', 'presentation')], max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('request', 'request'), ('in_progress', 'in_progress'), ('awaiting_approval', 'awaiting_approval'), ('completed', 'completed'), ('cancelled', 'cancelled'), ('refund_pending', 'refund_pending')], db_index=True, default='request', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='action',
            field=models.CharField(choices=[('create', 'create'), ('accept', 'accept'), ('reject', 'reject'), ('start', 'start'), ('deliver', 'deliver'), ('complete', 'complete'), ('auto_approve', 'auto_approve'), ('cancel', 'cancel'), ('refund_request', 'refund_request'), ('refund_approve', 'refund_approve'), ('refund_deny', 'refund_deny'), ('revise', 'revise'), ('update', 'update')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['writer', 'status'], name='orders_writer__5e6cc7_idx'),
        ),
    ]
