# Generated by Django 5.2.16 on 2026-07-25 10:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_approved_at_order_accepted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='level_adjusted',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='level_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='order',
            name='spacing',
            field=models.CharField(choices=[('single', 'single'), ('one_point_five', 'one_point_five'), ('double', 'double')], default='double', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='urgency_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='order',
            name='pages',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
