# Generated by Django 5.2.16 on 2026-07-25 14:55

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_base_price_order_level_adjusted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTimeline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('request', 'request'), ('in_progress', 'in_progress'), ('awaiting_approval', 'awaiting_approval'), ('completed', 'completed'), ('cancelled', 'cancelled'), ('declined', 'declined'), ('refund_pending', 'refund_pending')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(default='gray', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'order_timeline',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPresence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_online', models.BooleanField(default=False)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('current_room', models.CharField(blank=True, max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_presence',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='cancellation_feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='declined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='declined_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declined_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='declined_feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='declined_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_template',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='last_activity_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_group',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='parent_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='orders.order'),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='split_part',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='split_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='template_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='cancellation_reason',
            field=models.CharField(blank=True, choices=[('deadline_passed', 'Deadline passed with no response'), ('unsatisfied_quality', 'Unsatisfied with quality'), ('found_elsewhere', 'Found help elsewhere'), ('change_of_requirements', 'Changed requirements'), ('writer_communication', 'Poor writer communication'), ('other', 'Other reason')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('request', 'request'), ('in_progress', 'in_progress'), ('awaiting_approval', 'awaiting_approval'), ('completed', 'completed'), ('cancelled', 'cancelled'), ('declined', 'declined'), ('refund_pending', 'refund_pending')], db_index=True, default='request', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='subject',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='topic',
            field=models.CharField(db_index=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='action',
            field=models.CharField(choices=[('create', 'create'), ('accept', 'accept'), ('reject', 'reject'), ('start', 'start'), ('deliver', 'deliver'), ('complete', 'complete'), ('auto_approve', 'auto_approve'), ('cancel', 'cancel'), ('decline', 'decline'), ('resubmit', 'resubmit'), ('reorder', 'reorder'), ('split', 'split'), ('edit', 'edit'), ('refund_request', 'refund_request'), ('refund_approve', 'refund_approve'), ('refund_deny', 'refund_deny'), ('revise', 'revise'), ('update', 'update')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['parent_order'], name='orders_parent__a98c17_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_group'], name='orders_order_g_d53308_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'cancelled_at'], name='orders_status_a47297_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['last_activity_at'], name='orders_last_ac_380b1a_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number', 'topic'], name='orders_order_n_871848_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['student', 'order_number', 'topic'], name='orders_student_c17ec5_idx'),
        ),
        migrations.AddField(
            model_name='ordertimeline',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='orders.order'),
        ),
        migrations.AddField(
            model_name='userpresence',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='presence', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='ordertimeline',
            index=models.Index(fields=['order', 'created_at'], name='order_timel_order_i_f9ae04_idx'),
        ),
        migrations.AddIndex(
            model_name='userpresence',
            index=models.Index(fields=['user', 'is_online'], name='user_presen_user_id_dec1ad_idx'),
        ),
        migrations.AddIndex(
            model_name='userpresence',
            index=models.Index(fields=['last_seen_at'], name='user_presen_last_se_ef14aa_idx'),
        ),
    ]
