# Generated by Django 5.2.16 on 2026-07-25 15:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_ordertimeline_userpresence_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='orders_student_277d4a_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='orders_student_9a9891_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='orders_student_c17ec5_idx',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='student',
            new_name='client',
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['client', 'status'], name='orders_client__2e756d_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['client', 'created_at'], name='orders_client__bc22a2_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['client', 'order_number', 'topic'], name='orders_client__463ebb_idx'),
        ),
    ]
