# Generated by Django 5.2.16 on 2026-07-26 13:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_order_orders_student_277d4a_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['delivered_at'], name='attachments_deliver_509dc5_idx'),
        ),
    ]
