# Generated by Django 5.2.16 on 2026-08-06 07:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_attachment_delivered_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='auto_cancel_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='deadline_extended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='deadline_extension_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='is_late',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='action',
            field=models.CharField(choices=[('create', 'create'), ('accept', 'accept'), ('reject', 'reject'), ('start', 'start'), ('deliver', 'deliver'), ('complete', 'complete'), ('auto_approve', 'auto_approve'), ('cancel', 'cancel'), ('decline', 'decline'), ('resubmit', 'resubmit'), ('reorder', 'reorder'), ('split', 'split'), ('edit', 'edit'), ('refund_request', 'refund_request'), ('refund_approve', 'refund_approve'), ('refund_deny', 'refund_deny'), ('revise', 'revise'), ('update', 'update'), ('extend_deadline', 'extend_deadline'), ('mark_late', 'mark_late'), ('auto_cancel', 'auto_cancel')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['is_late'], name='orders_is_late_059617_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['auto_cancel_at'], name='orders_auto_ca_c89f06_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['deadline_extended_at'], name='orders_deadlin_27e2ae_idx'),
        ),
    ]
