# Generated by Django 6.0.3 on 2026-03-13 10:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=128)),
                ('phone', models.CharField(blank=True, max_length=17)),
                ('institution', models.CharField(blank=True, max_length=100)),
                ('verification_code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'pending_users',
                'indexes': [models.Index(fields=['email'], name='pending_use_email_0aca4e_idx'), models.Index(fields=['verification_code'], name='pending_use_verific_97f194_idx'), models.Index(fields=['expires_at'], name='pending_use_expires_f5c483_idx')],
            },
        ),
    ]
