# Generated by Django 5.2.16 on 2026-07-24 08:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_pendinguser'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('success', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'login_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RateLimit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('count', models.IntegerField(default=0)),
                ('window_start', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('window_end', models.DateTimeField()),
            ],
            options={
                'db_table': 'rate_limits',
            },
        ),
        migrations.RemoveIndex(
            model_name='pendinguser',
            name='pending_use_verific_97f194_idx',
        ),
        migrations.RemoveIndex(
            model_name='pendinguser',
            name='pending_use_expires_f5c483_idx',
        ),
        migrations.RenameField(
            model_name='pendinguser',
            old_name='verification_code',
            new_name='otp_code',
        ),
        migrations.RenameField(
            model_name='pendinguser',
            old_name='expires_at',
            new_name='otp_expires',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='verification_expires',
            new_name='otp_expires',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='course',
            new_name='otp_secret',
        ),
        migrations.RemoveField(
            model_name='user',
            name='display_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='verification_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='year_of_study',
        ),
        migrations.AddField(
            model_name='pendinguser',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pendinguser',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'client'), ('admin', 'admin')], db_index=True, default='client', max_length=10),
        ),
        migrations.AddIndex(
            model_name='pendinguser',
            index=models.Index(fields=['otp_code'], name='pending_use_otp_cod_e9ca77_idx'),
        ),
        migrations.AddIndex(
            model_name='pendinguser',
            index=models.Index(fields=['created_at'], name='pending_use_created_2c154b_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['created_at'], name='users_created_6541e9_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['last_login'], name='users_last_lo_65b80e_idx'),
        ),
        migrations.AddField(
            model_name='loginlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='ratelimit',
            index=models.Index(fields=['key', 'window_end'], name='rate_limits_key_b15065_idx'),
        ),
        migrations.AddIndex(
            model_name='loginlog',
            index=models.Index(fields=['email', 'created_at'], name='login_logs_email_6f58d6_idx'),
        ),
        migrations.AddIndex(
            model_name='loginlog',
            index=models.Index(fields=['ip_address', 'created_at'], name='login_logs_ip_addr_b15234_idx'),
        ),
        migrations.AddIndex(
            model_name='loginlog',
            index=models.Index(fields=['success'], name='login_logs_success_78daf7_idx'),
        ),
    ]
