# Generated by Django 5.2.16 on 2026-07-28 12:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_loginlog_ratelimit_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordChangeVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=6)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'password_change_verifications',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='google_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='password_change_code',
            field=models.CharField(blank=True, db_index=True, max_length=6),
        ),
        migrations.AddField(
            model_name='user',
            name='password_change_code_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password_change_temp',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('admin', 'Admin')], db_index=True, default='client', max_length=10),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['password_change_code'], name='users_passwor_ee244d_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['google_id'], name='users_google__d35fe6_idx'),
        ),
        migrations.AddField(
            model_name='passwordchangeverification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_verifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='passwordchangeverification',
            index=models.Index(fields=['user', 'created_at'], name='password_ch_user_id_83e777_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordchangeverification',
            index=models.Index(fields=['code'], name='password_ch_code_375bca_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordchangeverification',
            index=models.Index(fields=['expires_at'], name='password_ch_expires_35ab90_idx'),
        ),
    ]
