# Generated by Django 5.2.16 on 2026-07-30 05:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_passwordchangeverification_user_google_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('rate_limit_hit', 'Rate Limit Hit'), ('register_attempt', 'Registration Attempt'), ('register_success', 'Registration Success'), ('register_duplicate', 'Duplicate Registration'), ('otp_verification_failed', 'OTP Verification Failed'), ('email_send_failed', 'Email Send Failed'), ('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('login_user_not_found', 'Login User Not Found'), ('account_locked', 'Account Locked'), ('token_refresh_failed', 'Token Refresh Failed'), ('password_reset', 'Password Reset'), ('password_changed', 'Password Changed'), ('google_callback_no_code', 'Google Callback No Code'), ('google_token_exchange_failed', 'Google Token Exchange Failed'), ('google_token_verification_failed', 'Google Token Verification Failed'), ('google_login_success', 'Google Login Success'), ('google_signup_redirect', 'Google Signup Redirect'), ('google_signup_success', 'Google Signup Success'), ('google_signup_rollback', 'Google Signup Rollback')], db_index=True, max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Security Event',
                'verbose_name_plural': 'Security Events',
                'db_table': 'security_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', '-created_at'], name='security_ev_event_t_33b3e5_idx'), models.Index(fields=['user', '-created_at'], name='security_ev_user_id_c77a93_idx'), models.Index(fields=['ip_address', '-created_at'], name='security_ev_ip_addr_48a73a_idx')],
            },
        ),
    ]
