# Generated by Django 5.2.16 on 2026-08-07 08:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_clientnotification'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='passwordchangeverification',
            name='password_ch_code_375bca_idx',
        ),
        migrations.RemoveIndex(
            model_name='pendinguser',
            name='pending_use_otp_cod_e9ca77_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_passwor_dda668_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_passwor_ee244d_idx',
        ),
        migrations.RemoveField(
            model_name='passwordchangeverification',
            name='code',
        ),
        migrations.RemoveField(
            model_name='pendinguser',
            name='otp_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='otp_secret',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password_change_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password_change_code_expires',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password_change_temp',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password_reset_token',
        ),
        migrations.AddField(
            model_name='passwordchangeverification',
            name='code_hash',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='pendinguser',
            name='otp_code_hash',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='apple_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_secret_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='password_reset_token_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='event_type',
            field=models.CharField(choices=[('rate_limit_hit', 'Rate Limit Hit'), ('register_attempt', 'Registration Attempt'), ('register_success', 'Registration Success'), ('register_duplicate', 'Duplicate Registration'), ('otp_verification_failed', 'OTP Verification Failed'), ('email_send_failed', 'Email Send Failed'), ('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('login_user_not_found', 'Login User Not Found'), ('account_locked', 'Account Locked'), ('token_refresh_failed', 'Token Refresh Failed'), ('password_reset', 'Password Reset'), ('password_changed', 'Password Changed'), ('google_callback_no_code', 'Google Callback No Code'), ('google_token_exchange_failed', 'Google Token Exchange Failed'), ('google_token_verification_failed', 'Google Token Verification Failed'), ('google_login_success', 'Google Login Success'), ('google_signup_redirect', 'Google Signup Redirect'), ('google_signup_success', 'Google Signup Success'), ('google_signup_rollback', 'Google Signup Rollback'), ('apple_callback_no_code', 'Apple Callback No Code'), ('apple_token_exchange_failed', 'Apple Token Exchange Failed'), ('apple_token_verification_failed', 'Apple Token Verification Failed'), ('apple_login_success', 'Apple Login Success'), ('apple_signup_redirect', 'Apple Signup Redirect'), ('apple_signup_success', 'Apple Signup Success'), ('apple_signup_rollback', 'Apple Signup Rollback')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='google_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(regex='^\\+?[1-9]\\d{1,14}$')]),
        ),
        migrations.AddIndex(
            model_name='passwordchangeverification',
            index=models.Index(fields=['code_hash'], name='password_ch_code_ha_e267a8_idx'),
        ),
        migrations.AddIndex(
            model_name='pendinguser',
            index=models.Index(fields=['otp_code_hash'], name='pending_use_otp_cod_46d1ac_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['password_reset_token_hash'], name='users_passwor_c7e24c_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['apple_id'], name='users_apple_i_8f59ea_idx'),
        ),
    ]
