# Generated by Django 5.2.16 on 2026-08-07 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_passwordchangeverification_password_ch_code_375bca_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordchangeverification',
            name='temp_password_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
