# Generated by Django 6.0.3 on 2026-03-13 20:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypingStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_typing', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'typing_statuses',
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='admin_last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='student_last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='is_recalled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='recalled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'text'), ('file', 'file'), ('system', 'system'), ('edited', 'edited'), ('recalled', 'recalled')], default='text', max_length=10),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_recalled'], name='messages_is_reca_e81c03_idx'),
        ),
        migrations.AddField(
            model_name='typingstatus',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typing_statuses', to='messaging.conversation'),
        ),
        migrations.AddField(
            model_name='typingstatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='typingstatus',
            index=models.Index(fields=['conversation', 'updated_at'], name='typing_stat_convers_0ad727_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='typingstatus',
            unique_together={('conversation', 'user')},
        ),
    ]
