# Generated by Django 5.2.16 on 2026-07-25 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_alter_conversation_options_and_more'),
        ('orders', '0006_remove_order_orders_student_277d4a_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='conversation',
            name='conversatio_student_2309aa_idx',
        ),
        migrations.RenameField(
            model_name='conversation',
            old_name='student_last_seen',
            new_name='client_last_seen',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='student',
        ),
        migrations.AddField(
            model_name='conversation',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='client_conversations', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['client', 'last_message_at'], name='conversatio_client__a083be_idx'),
        ),
    ]
