# Generated by Django 5.2.16 on 2026-07-26 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_remove_conversation_conversatio_student_2309aa_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='message',
            name='messages_is_reca_e81c03_idx',
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_recalled',
        ),
        migrations.RemoveField(
            model_name='message',
            name='recalled_at',
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'text'), ('file', 'file'), ('system', 'system'), ('edited', 'edited')], default='text', max_length=10),
        ),
    ]
