# Generated by Django 6.0.3 on 2026-03-13 19:05

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_attachment_attachments_is_mali_aa03b6_idx_and_more'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardAuthorization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('authorization_code', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='authorized', max_length=20)),
                ('provider_response', models.JSONField(default=dict)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'card_authorizations',
            },
        ),
        migrations.CreateModel(
            name='FraudCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('risk_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('risk_level', models.CharField(max_length=20)),
                ('ip_risk', models.FloatField(default=0)),
                ('device_risk', models.FloatField(default=0)),
                ('amount_risk', models.FloatField(default=0)),
                ('velocity_risk', models.FloatField(default=0)),
                ('flags', models.JSONField(default=list)),
                ('is_blocked', models.BooleanField(default=False)),
                ('requires_review', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'fraud_checks',
            },
        ),
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='held', max_length=20)),
                ('held_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('auto_release_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'order_payments',
            },
        ),
        migrations.CreateModel(
            name='PaymentIntent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('intent_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('processing', 'processing'), ('succeeded', 'succeeded'), ('failed', 'failed'), ('requires_action', 'requires_action')], default='pending', max_length=20)),
                ('client_secret', models.CharField(max_length=255)),
                ('return_url', models.URLField(blank=True)),
                ('metadata', models.JSONField(default=dict)),
                ('provider_response', models.JSONField(default=dict)),
                ('next_action', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'payment_intents',
            },
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='billing_address_line1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='billing_address_line2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='billing_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='billing_country',
            field=models.CharField(default='US', max_length=2),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='billing_postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='billing_state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='cardholder_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='fingerprint',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='last_used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='payout',
            name='provider_response',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='payout',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='held_after',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='held_before',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='signature',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='wallet',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='wallet',
            name='failed_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wallet',
            name='held_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='wallet',
            name='last_failed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='pending_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='wallet',
            name='total_withdrawn',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='card_brand',
            field=models.CharField(blank=True, choices=[('visa', 'Visa'), ('mastercard', 'Mastercard'), ('amex', 'American Express'), ('discover', 'Discover'), ('jcb', 'JCB'), ('diners', 'Diners Club')], max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='expiry_month',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='expiry_year',
            field=models.IntegerField(default=2025, validators=[django.core.validators.MinValueValidator(2020), django.core.validators.MaxValueValidator(2100)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='last_four',
            field=models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='provider_method_id',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('stripe', 'stripe'), ('paypal', 'paypal'), ('wallet', 'wallet'), ('admin', 'admin'), ('card', 'card')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('processing', 'processing'), ('completed', 'completed'), ('failed', 'failed'), ('cancelled', 'cancelled'), ('held', 'held')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('deposit', 'deposit'), ('payment', 'payment'), ('refund', 'refund'), ('withdrawal', 'withdrawal'), ('adjustment', 'adjustment'), ('hold', 'hold'), ('release', 'release'), ('settle', 'settle')], db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='paymentmethod',
            index=models.Index(fields=['fingerprint'], name='payment_met_fingerp_e7ce47_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentmethod',
            index=models.Index(fields=['expiry_year', 'expiry_month'], name='payment_met_expiry__7013ba_idx'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['provider_payout_id'], name='payouts_provide_92a3af_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['signature'], name='transaction_signatu_3e6425_idx'),
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['pending_balance'], name='wallets_pending_a61a90_idx'),
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['held_balance'], name='wallets_held_ba_7a5e75_idx'),
        ),
        migrations.AddField(
            model_name='cardauthorization',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.paymentmethod'),
        ),
        migrations.AddField(
            model_name='cardauthorization',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_authorizations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fraudcheck',
            name='reviewed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_frauds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fraudcheck',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_checks', to='payments.transaction'),
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order'),
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='released_to_admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_payments', to='payments.transaction'),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.paymentmethod'),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.transaction'),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_intents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='cardauthorization',
            index=models.Index(fields=['user', 'status'], name='card_author_user_id_afb255_idx'),
        ),
        migrations.AddIndex(
            model_name='cardauthorization',
            index=models.Index(fields=['authorization_code'], name='card_author_authori_256f15_idx'),
        ),
        migrations.AddIndex(
            model_name='cardauthorization',
            index=models.Index(fields=['expires_at'], name='card_author_expires_780ad8_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudcheck',
            index=models.Index(fields=['risk_level'], name='fraud_check_risk_le_1a27ad_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudcheck',
            index=models.Index(fields=['requires_review'], name='fraud_check_require_de4801_idx'),
        ),
        migrations.AddIndex(
            model_name='orderpayment',
            index=models.Index(fields=['order', 'status'], name='order_payme_order_i_b14fa2_idx'),
        ),
        migrations.AddIndex(
            model_name='orderpayment',
            index=models.Index(fields=['auto_release_at'], name='order_payme_auto_re_23c959_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['user', 'status'], name='payment_int_user_id_f69c6d_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['intent_id'], name='payment_int_intent__771a2e_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['expires_at'], name='payment_int_expires_65ff25_idx'),
        ),
    ]
