# Generated by Django 5.2.16 on 2026-07-24 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_approved_at_order_accepted_at_and_more'),
        ('payments', '0002_cardauthorization_fraudcheck_orderpayment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardauthorization',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='cardauthorization',
            name='user',
        ),
        migrations.RemoveIndex(
            model_name='orderpayment',
            name='order_payme_order_i_b14fa2_idx',
        ),
        migrations.RemoveIndex(
            model_name='wallet',
            name='wallets_pending_a61a90_idx',
        ),
        migrations.RemoveField(
            model_name='orderpayment',
            name='released_to_admin',
        ),
        migrations.RemoveField(
            model_name='orderpayment',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='pending_balance',
        ),
        migrations.AddField(
            model_name='fraudcheck',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fraud_checks', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='hold_transaction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='order_payment_holds', to='payments.transaction'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='release_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_payment_releases', to='payments.transaction'),
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='released_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_order_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payout',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payout', to='payments.transaction'),
        ),
        migrations.AlterField(
            model_name='fraudcheck',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_frauds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fraudcheck',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fraud_checks', to='payments.transaction'),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='auto_release_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='status',
            field=models.CharField(choices=[('held', 'held'), ('released', 'released'), ('refunded', 'refunded')], default='held', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('stripe', 'stripe'), ('paypal', 'paypal'), ('wallet', 'wallet'), ('admin', 'admin'), ('system', 'system')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('processing', 'processing'), ('completed', 'completed'), ('failed', 'failed'), ('cancelled', 'cancelled')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('deposit', 'deposit'), ('hold', 'hold'), ('release', 'release'), ('settle', 'settle'), ('refund', 'refund'), ('payout', 'payout'), ('withdrawal', 'withdrawal'), ('adjustment', 'adjustment')], db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='orderpayment',
            index=models.Index(fields=['status'], name='order_payme_status_07c88a_idx'),
        ),
        migrations.DeleteModel(
            name='CardAuthorization',
        ),
    ]
