# Generated by Django 5.2.16 on 2026-07-27 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_remove_fraudcheck_reviewed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='verification_code_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
