# Generated by Django 5.2.16 on 2026-07-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_paymentmethod_verification_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='verification_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='verification_locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
