from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework_simplejwt.views import TokenRefreshView
from . import views
from apps.admin_portal.views import admin_order_detail, admin_contact_messages, admin_contact_message_read, admin_contact_message_delete
from apps.orders.views import order_paypal_success, order_paypal_cancel
from apps.accounts.views import (
    client_notifications_list,
    client_notification_mark_read,
    client_notifications_mark_all_read,
    client_notification_delete,
    client_notifications_unread_count,
    profile,
)

app_name = 'config'

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.login_page, name='login'),
    path('register/', views.register_page, name='register'),
    path('forgot-password/', views.forgot_password_page, name='forgot-password'),
    path('reset-password/<str:token>/', views.reset_password_page, name='reset-password'),
    path('about/', views.about, name='about'),
    path('api/about/stats/', views.about_stats, name='about-stats'),
    path('services/', views.services, name='services'),
    path('samples/', views.samples, name='samples'),
    path('samples/<uuid:sample_id>/download/', views.download_sample, name='download-sample'),
    path('pricing/', views.pricing, name='pricing'),
    path('how-it-works/', views.how_it_works, name='how-it-works'),
    path('faq/', views.faq, name='faq'),
    path('contact/', views.contact, name='contact'),
    path('contact/send/', views.contact_message, name='contact-send'),
    path('contact/submit/', views.contact_message, name='contact-submit'),
    path('terms/', views.terms, name='terms'),
    path('privacy/', views.privacy, name='privacy'),
    path('refund-policy/', views.refund_policy, name='refund-policy'),
    path('guarantees/', views.guarantees, name='guarantees'),
    path('testimonials/', views.testimonials, name='testimonials'),
    path('place-order/', views.place_order, name='place-order'),
    path('blog/', views.blog, name='blog'),
    path('blog/<slug:slug>/', views.blog_detail, name='blog-detail'),
    path('blog/<slug:slug>/share/', views.blog_share, name='blog-share'),
    path('api/blog/search/', views.blog_search_suggestions, name='blog-search-suggestions'),
    path('dashboard/', views.dashboard_redirect, name='dashboard'),
    path('client/dashboard/', views.client_dashboard, name='client-dashboard'),
    path('client/orders/', views.client_orders, name='client-orders'),
    path('client/orders/new/', views.client_new_order, name='client-new-order'),
    path('client/orders/<uuid:order_id>/', views.client_order_detail, name='client-order-detail'),
    path('client/orders/<uuid:order_id>/paypal/success/', order_paypal_success, name='order-paypal-success'),
    path('client/orders/<uuid:order_id>/paypal/cancel/', order_paypal_cancel, name='order-paypal-cancel'),
    path('client/wallet/', views.client_wallet, name='client-wallet'),
    path('client/messages/', views.client_messages, name='client-messages'),
    path('client/messages/<uuid:order_id>/', views.client_order_messages, name='client-order-messages'),
    path('client/announcements/', views.client_announcements, name='client-announcements'),
    path('client/profile/', views.client_profile, name='client-profile'),
    path('client/profile/edit/', views.client_profile_edit, name='client-profile-edit'),
    path('client/settings/', views.client_settings, name='client-settings'),
    path('client/notifications/', views.client_notifications, name='client-notifications'),
    path('admin-portal/dashboard/', views.admin_dashboard_view, name='admin-dashboard'),
    path('admin-portal/orders/', views.admin_orders, name='admin-orders'),
    path('admin-portal/orders/<uuid:order_id>/', admin_order_detail, name='admin-order-detail'),
    path('admin-portal/orders/<uuid:order_id>/workspace/', views.admin_order_workspace, name='admin-order-workspace'),
    path('admin-portal/users/', views.admin_users, name='admin-users'),
    path('admin-portal/users/<uuid:user_id>/', views.admin_user_detail, name='admin-user-detail'),
    path('admin-portal/finances/', views.admin_finances, name='admin-finances'),
    path('admin-portal/refunds/', views.admin_refunds, name='admin-refunds'),
    path('admin-portal/messages/', views.admin_messages, name='admin-messages'),
    path('admin-portal/blog/', views.admin_blog, name='admin-blog'),
    path('admin-portal/blog/create/', views.admin_create_blog, name='admin-create-blog'),
    path('admin-portal/blog/<uuid:blog_id>/edit/', views.admin_edit_blog, name='admin-edit-blog'),
    path('admin-portal/blog/<uuid:blog_id>/delete/', views.admin_delete_blog_ajax, name='admin-delete-blog'),
    path('admin-portal/blog/<uuid:blog_id>/toggle/', views.admin_toggle_blog_status, name='admin-toggle-blog'),
    path('api/admin/blog/<uuid:blog_id>/detail/', views.admin_blog_detail, name='admin-blog-detail'),
    path('api/admin/blog/search/', views.admin_blog_search_suggestions, name='admin-blog-search-suggestions'),
    path('admin-portal/samples/', views.admin_samples, name='admin-samples'),
    path('admin-portal/samples/<uuid:sample_id>/toggle/', views.admin_toggle_sample, name='admin-toggle-sample'),
    path('admin-portal/samples/<uuid:sample_id>/delete/', views.admin_delete_sample, name='admin-delete-sample'),
    path('admin-portal/content/', views.admin_content, name='admin-content'),
    path('admin-portal/logs/', views.admin_logs, name='admin-logs'),
    path('admin-portal/settings/', views.admin_settings, name='admin-settings'),
    path('admin-portal/profile/', views.admin_profile, name='admin-profile'),
    path('admin-portal/notifications/', views.admin_notifications, name='admin-notifications'),
    path('admin-portal/contact-messages/', admin_contact_messages, name='admin-contact-messages'),
    path('admin-portal/contact-messages/<uuid:message_id>/read/', admin_contact_message_read, name='admin-contact-message-read'),
    path('admin-portal/contact-messages/<uuid:message_id>/delete/', admin_contact_message_delete, name='admin-contact-message-delete'),
    path('django-admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('auth/', include('apps.accounts.urls')),
    path('api/v1/auth/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/v1/auth/', include('apps.accounts.urls')),
    path('api/v1/auth/profile/', profile, name='api-profile'),
    path('api/v1/admin/', include('apps.admin_portal.urls')),
    path('api/v1/messaging/', include('apps.messaging.urls')),
    path('api/v1/orders/', include('apps.orders.urls')),
    path('api/v1/wallet/', include('apps.payments.urls')),
    path('api/v1/client/counts/', views.client_counts, name='client-counts'),
    path('api/v1/client/orders/', views.client_orders_data, name='client-orders-data'),
    path('api/v1/client/orders/<uuid:order_id>/', views.client_order_detail_data, name='client-order-detail-data'),
    path('api/v1/client/orders/<uuid:order_id>/cancel/', views.client_cancel_order, name='client-cancel-order'),
    path('api/v1/client/orders/<uuid:order_id>/approve/', views.client_approve_order, name='client-approve-order'),
    path('api/v1/client/orders/<uuid:order_id>/revision/', views.client_request_revision, name='client-request-revision'),
    path('api/v1/client/orders/<uuid:order_id>/rate/', views.client_rate_order, name='client-rate-order'),
    path('api/v1/admin/counts/', views.admin_counts, name='admin-counts'),
    path('api/v1/client/notifications/', client_notifications_list, name='client-notifications-list'),
    path('api/v1/client/notifications/<uuid:notification_id>/read/', client_notification_mark_read, name='client-notification-mark-read'),
    path('api/v1/client/notifications/mark-all-read/', client_notifications_mark_all_read, name='client-notifications-mark-all-read'),
    path('api/v1/client/notifications/<uuid:notification_id>/delete/', client_notification_delete, name='client-notification-delete'),
    path('api/v1/client/notifications/unread-count/', client_notifications_unread_count, name='client-notifications-unread-count'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)