# Generated by Django 5.2.16 on 2026-07-24 10:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0001_initial'),
        ('orders', '0002_remove_attachment_attachments_is_mali_aa03b6_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('is_pinned', models.BooleanField(db_index=True, default=False)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'admin_notes',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-starts_at']},
        ),
        migrations.AlterModelOptions(
            name='platformstats',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='announcement',
            name='target_audience',
            field=models.CharField(choices=[('all', 'All Users'), ('clients', 'Clients Only'), ('admin', 'Admin Only')], default='all', max_length=10),
        ),
        migrations.AddField(
            model_name='announcement',
            name='viewed_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='platformstats',
            name='completion_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='platformstats',
            name='overdue_orders',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='platformstats',
            name='pending_payments',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='adminactionlog',
            name='action_type',
            field=models.CharField(choices=[('user_suspend', 'Suspend User'), ('user_reactivate', 'Reactivate User'), ('user_delete', 'Delete User'), ('order_approve', 'Approve Order'), ('order_reject', 'Reject Order'), ('order_start', 'Start Order'), ('order_deliver', 'Deliver Order'), ('order_complete', 'Complete Order'), ('refund_approve', 'Approve Refund'), ('refund_deny', 'Deny Refund'), ('payment_release', 'Release Payment'), ('content_edit', 'Edit Content'), ('settings_change', 'Change Setting'), ('wallet_adjust', 'Adjust Wallet'), ('announcement_create', 'Create Announcement'), ('announcement_update', 'Update Announcement')], db_index=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='adminactionlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], db_index=True, default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='starts_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('boolean', 'Boolean'), ('json', 'JSON'), ('email', 'Email'), ('url', 'URL')], default='text', max_length=20),
        ),
        migrations.AddIndex(
            model_name='adminactionlog',
            index=models.Index(fields=['created_at'], name='admin_actio_created_6f9b1f_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['target_audience'], name='announcemen_target__e32955_idx'),
        ),
        migrations.AddIndex(
            model_name='platformstats',
            index=models.Index(fields=['date', 'created_at'], name='platform_st_date_e4d10b_idx'),
        ),
        migrations.AddIndex(
            model_name='sitecontent',
            index=models.Index(fields=['section'], name='site_conten_section_a98472_idx'),
        ),
        migrations.AddIndex(
            model_name='systemsetting',
            index=models.Index(fields=['key'], name='system_sett_key_052b30_idx'),
        ),
        migrations.AddIndex(
            model_name='systemsetting',
            index=models.Index(fields=['is_public'], name='system_sett_is_publ_c2e919_idx'),
        ),
        migrations.AddField(
            model_name='adminnote',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminnote',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_notes_about', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminnote',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order'),
        ),
        migrations.AddIndex(
            model_name='adminnote',
            index=models.Index(fields=['admin', 'is_pinned'], name='admin_notes_admin_i_90104f_idx'),
        ),
        migrations.AddIndex(
            model_name='adminnote',
            index=models.Index(fields=['admin', 'is_archived'], name='admin_notes_admin_i_dc8e62_idx'),
        ),
        migrations.AddIndex(
            model_name='adminnote',
            index=models.Index(fields=['order'], name='admin_notes_order_i_39ba3e_idx'),
        ),
        migrations.AddIndex(
            model_name='adminnote',
            index=models.Index(fields=['client'], name='admin_notes_client__51c3b1_idx'),
        ),
    ]
