# Generated by Django 5.2.16 on 2026-07-25 10:58

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0002_adminnote_alter_announcement_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminactionlog',
            name='action_type',
            field=models.CharField(choices=[('user_suspend', 'Suspend User'), ('user_reactivate', 'Reactivate User'), ('user_delete', 'Delete User'), ('order_approve', 'Approve Order'), ('order_reject', 'Reject Order'), ('order_start', 'Start Order'), ('order_deliver', 'Deliver Order'), ('order_complete', 'Complete Order'), ('refund_approve', 'Approve Refund'), ('refund_deny', 'Deny Refund'), ('payment_release', 'Release Payment'), ('content_edit', 'Edit Content'), ('settings_change', 'Change Setting'), ('wallet_adjust', 'Adjust Wallet'), ('blog_create', 'Create Blog Post'), ('blog_update', 'Update Blog Post'), ('blog_delete', 'Delete Blog Post')], db_index=True, max_length=25),
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('excerpt', models.TextField(max_length=300)),
                ('content', models.TextField()),
                ('published_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'blog_posts',
                'ordering': ['-published_at'],
            },
        ),
        migrations.DeleteModel(
            name='Announcement',
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['slug'], name='blog_posts_slug_b4ca25_idx'),
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['published_at'], name='blog_posts_publish_fc0698_idx'),
        ),
        migrations.AddIndex(
            model_name='blog',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title', 'content', 'excerpt'], name='blog_posts_title_38f944_gin'),
        ),
    ]
