# Generated by Django 5.2.16 on 2026-07-25 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0004_sample'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='shares',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
