# Generated by Django 5.2.16 on 2026-08-12 14:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0007_contactmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='blog',
            name='blog_posts_title_38f944_gin',
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['title', 'content', 'excerpt'], name='blog_posts_title_7665ad_idx'),
        ),
    ]
